name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 20.127.72.62
        username: sample
        password: Password@123
        port: 22
        script: |
                whoami
                cd /srv/Snipe-IT-GitHub-Actions
                sudo git pull origin devcontainer
                sudo docker compose up --build -d
